name: "Build docs and push to Pages"
on:
  push:
    branches:
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir build
      - name: Install doxygen
        run: sudo apt install -y doxygen graphviz
      - name: Make Doxygen docs
        working-directory: build
        run: |
          cmake ../docs
          make doxygen
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install reqs
        working-directory: docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build sphinx documentation
        working-directory: docs
        run: |
          sed -i "/segment_analytics/s/^#//" source/conf.py
          make html
          touch build/html/.nojekyll
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_WRITE_TOKEN }}
          BASE_BRANCH: gh-actions # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build/html # The folder the action should deploy.
          #BUILD_SCRIPT: npm install && npm run-script build # The build script
